### ISSUE TITLE
Korean Font

### ISSUE THREAD

**Issue by krulkip** [takkaO/M5FontRender#1]
Hello, Thank you very much for this nice and user friendly option to render japanese and chinese fonts.
It works for me just as planned. When i try to add some korean eg by render.printf("안녕하세요 세계\n");
I get dots meaning the unicode has not been added. How can i do that for the hangul characters

**Comment by takkaO** [comment]
**Hello, krulkip !**
**Thank you for using this program.**

As you have guessed, the dots mean that the font file does not contain the specified characters.
If you are using the fonts in the sample program, then unfortunately Hangul is not supported.
It's easy to solve this problem. You just use the other TTF font.
If you want to display Hangul characters, there are TTF fonts that support Hangul such as [SWAGGER font](http://swagger.kr/font_download.html) and [Solmee font](https://company.gabia.com/font) and so on.
I have tried these fonts and they seem to display well ! ( I can't read Hangul so I don't know if I'm really right lol. )

![IMG_0355](https://user-images.githubusercontent.com/46308252/107223744-e31e9d00-6a59-11eb-9788-40142a804d26.jpg)

**Comment by krulkip** [comment]
Thats fantastic thank you. It now works with an SD card. Can it also work from SPIFFS ?


Sent from Yahoo Mail for iPad


On Monday, February 8, 2021, 14:14, takkaO <notifications@github.com> wrote:




Hello, krulkip !
Thank you for using this program.

As you have guessed, the dots mean that the font file does not contain the specified characters.
If you are using the fonts in the sample program, then unfortunately Hangul is not supported.
It's easy to solve this problem. You just use the other TTF font.
If you want to display Hangul characters, there are TTF fonts that support Hangul such as SWAGGER font and Solmee font and so on.
I have tried these fonts and they seem to display well ! ( I can't read Hangul so I don't know if I'm really right lol. )

**Comment by takkaO** [comment]
I'm glad you were able to make it work.

This library does not currently support loading fonts from SPIFFS. 
The reason for this is that it is too cumbersome to manage the files in SPIFFS.
If you want to load fonts without an SD card, there is a way to embed fonts in the source code.
To convert TTF font file to C header file, use ```tools/ttf2bin/ttf2bin.py``` in this repo (```ttf2bin.py``` is provided by M5EPD).

```sh
> python3 ttf2bin.py your_ttf_file
```

How to use after this, please refer to ```Load TTF from binary file```.

If the size of the TTF file is too large, try compressing the TTF font or change the ESP32 Partition Scheme.
